Isaac bullinger gitpod exploration
clockwise-software/copper pull request #22
Opened 2021-04-01 03:15 UTC by isaacBullinger

Made separate pages with update and delete for the database. Added email, registered licenses and city into the add page.  I don't know if it manipulates the data because the backend is disabled. Review thoroughly!

2021-04-01 16:12 UTC, andey-robins requested changes
@isaacBullinger can you make the changes to fix that database back to the right one?

i’ll finish reviewing everything else then! :)

2021-04-01 16:44 UTC, isaacBullinger commented
Ok, I made the change. Sorry about that.

2021-04-01 20:12 UTC, andey-robins commented
Hey you're good! No need to apologize :) That's why we review it, to make sure that everyone is on the same page!

Next thing to do, let's squash some of these commits. Throwing 25 new commits into the repo will make it difficult for people to understand what changes are happening where and in what places. Try to pick the top two or three commits from this list, give them descriptive names, and then squash the rest into those. [Here's a nice explanation of how (when and why) to squash commits!](https://www.git-tower.com/learn/git/faq/git-squash/).

If you have questions, or just want someone to help as you go through the process since making changes to git is definitely intimidating, ask in the git related slack channel!

@isaacBullinger

2021-04-02 01:12 UTC, isaacBullinger commented
I can enter the rebase but whenever I try to squash it doesn't save the file and merge them.

2021-04-02 01:22 UTC, andey-robins commented
Let's see if we can summon someone who has more familiarity with gitpod than I do

@dr-mikeb @masonj188 @dradosevich @mthoney

2021-04-02 03:43 UTC, isaacBullinger commented
Merge conflict fixed, squash commits on merge.

2021-04-02 03:52 UTC, swolf4070 commented
^^ There is an option while merging to squash the commits, super easy, no rebase necessary

2021-04-02 20:56 UTC, andey-robins requested changes

2021-04-02 20:56 UTC, andey-robins commented on src/SimpleServer.py
> +	if request.method =='POST':
This post method never runs on my end. When I actually click to submit an additional Employee's data, all that the server sees is a GET request with the query string you constructed.

2021-04-02 20:56 UTC, andey-robins commented on src/SimpleServer.py
> +			cur.execute("INSERT INTO EmployeeList ('FirstName', 'LastName', 'Business Unit', 'State/Province', 'City', 'Registered Licenses')\
This SQL string looks right to me, so good there :)

It should just need the above mentioned fix to get the query happening properly

2021-04-02 20:56 UTC, andey-robins commented on src/templates/EmployeeData.html
> +    params = 'email'+email'&firstName='+firstName+'&lastName='+lastName+'&bu='+businessunit+'&state='+state'&city'+city'&rl'+rl; // Added email, city and registered licenses.
I'm not sure what happened to break the POST options in this file, but perhaps looking at this query string might be a place to start? That's very much a shot in the dark though, cause it looks right to me at first glance.

2021-04-02 20:58 UTC, andey-robins commented on src/SimpleServer.py
> +	if request.method =='POST':
<img width="651" alt="image" src="https://user-images.githubusercontent.com/43155608/113453742-e3854580-93c3-11eb-89f2-1d3615b10d50.png">

2021-04-02 21:00 UTC, andey-robins commented on src/SimpleServer.py
> +	if request.method =='POST':
Above is my server's console when I hit enter on the AddEmployee Page. I believe that immediately following that third entry there needs to be a post request like in the image below (which is what is currently on `main` and supports the insertion of new employees)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/43155608/113453886-33fca300-93c4-11eb-9873-52f8d5492104.png">

2021-04-03 15:12 UTC, isaacBullinger commented on src/templates/EmployeeData.html
> +    params = 'email'+email'&firstName='+firstName+'&lastName='+lastName+'&bu='+businessunit+'&state='+state'&city'+city'&rl'+rl; // Added email, city and registered licenses.
I forgot to add some + signs between some of the variables I added in params, it is posting now.

2021-04-03 15:30 UTC, andey-robins requested changes
Way to go getting the POST to work!

It still looks like the changes aren't happening in the database. I'll take a look at it during our lunch to debug why that might be happening :)

2021-04-03 15:42 UTC, andey-robins approved these changes
Actually, I just went through to read the issues and saw that this is just a frontend fix :) Good work there @isaacBullinger

2021-04-03 15:58 UTC, mwodahl approved these changes
Looks good

2021-04-03 15:59 UTC, merged